### ISSUE TITLE
Convert fedora docker to flist throws an error

### ISSUE THREAD

**Issue by islamTaha12** [zero-os/0-hub#24]
I tried to convert this image https://hub.docker.com/_/fedora

**Actual result**
![image](https://user-images.githubusercontent.com/17981089/28519342-8000cb3a-706b-11e7-8bd7-9ab79d50e00f.png)

```bash
Traceback (most recent call last)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/lib/python3/dist-packages/werkzeug/contrib/fixers.py", line 148, in __call__
return self.app(environ, start_response)
File "/mnt/hub/hub-staging/python/flist-uploader.py", line 50, in __call__
return self.app(environ, start_response)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/usr/lib/python3/dist-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
raise value
File "/usr/lib/python3/dist-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
raise value
File "/usr/lib/python3/dist-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/mnt/hub/hub-staging/python/flist-uploader.py", line 623, in docker_handler
return handle_docker_import(request.form.get("docker-input"))
File "/mnt/hub/hub-staging/python/flist-uploader.py", line 227, in handle_docker_import
cn = dockerclient.containers.create(dockerimage, name=dockername, hostname=dockername)
File "/usr/local/lib/python3.5/dist-packages/docker/models/containers.py", line 701, in create
resp = self.client.api.create_container(**create_kwargs)
File "/usr/local/lib/python3.5/dist-packages/docker/api/container.py", line 446, in create_container
return self.create_container_from_config(config, name)
File "/usr/local/lib/python3.5/dist-packages/docker/api/container.py", line 457, in create_container_from_config
return self._result(res, True)
File "/usr/local/lib/python3.5/dist-packages/docker/api/client.py", line 220, in _result
self._raise_for_status(response)
File "/usr/local/lib/python3.5/dist-packages/docker/api/client.py", line 216, in _raise_for_status
raise create_api_error_from_http_exception(e)
File "/usr/local/lib/python3.5/dist-packages/docker/errors.py", line 30, in create_api_error_from_http_exception
raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request for url: http+docker://localunixsocket/v1.24/containers/create?name=17382486496b4e75bc8cb83812814b73 ("No command specified")
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.
```

**Comment by maxux** [comment]
Fixed on staging
